controller_frequency: 5.0

RobotinoLocalPlanner:
  max_linear_vel: 0.8
  mix_linear_vel: 0.1
  max_rotation_vel: 1.0
  min_rotation_vel: 0.3

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  
  heading_lookahead: 0.3
  num_window_points: 10
  
TrajectoryPlannerROS:
#from turtlebot
  max_vel_x: 0.40
  min_vel_x: 0.10
  max_rotational_vel: 1.2
  min_in_place_rotational_vel: 1.0
  acc_lim_th: 0.75
  acc_lim_x: 0.50
  acc_lim_y: 0.50

  holonomic_robot: true
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.25
  goal_distance_bias: 0.8
  path_distance_bias: 0.8
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  meter_scoring: true

  vx_samples: 6
  vtheta_samples: 20
  dwa: false
